### ISSUE TITLE
Not able to setup http2 in exercise 1

### ISSUE THREAD

**Issue by bhupendra1011** [mike-works/pwa-fundamentals#142]
HI All ,

 I am not able to setup http2 server in exercise 1 of PWA & Offline course . When I run n**pm run watch --http2** ( as ./run serve is depreacted) , and start page: https://localhost:5000 nothing loads , and on localhost:3000 , all files are served over http 1.1 . Also I noticed when I open webpage in mobile by using system IP address , server crashes . ] events.js:183
[UI] throw er; // Unhandled 'error' event
[UI] ^
[UI]
[UI] Error: read ECONNRESET
[UI] at _errnoException (util.js:1024:11)
[UI] at TCP.onread (net.js:615:25)

Here is the commit id of exercise 1: https://github.com/bhupendra1011/pwa-fundamentals/commit/3fe6e128d9349ae5dc8a8cd7a93cc2ab3cf0cf39

**Comment by mike-north** [comment]
Does HTTP 1.1 on `:3000` work for you?

**Comment by bhupendra1011** [comment]
Hi @mike-north  , Yes I do get HTTP 1.1 on localhost:3000
<img width="1151" alt="screen shot 2018-08-08 at 1 33 52 pm" src="https://user-images.githubusercontent.com/5452261/43824636-27b59f7a-9b10-11e8-83c3-2735de4c3b2c.png">
